### PR TITLE
add update for 9/8/17

### PR DESCRIPTION
**Pull request by afeld**
Anything I missed? Any way it could be more clear?

### CODE REVIEW

**Review by timothybjones — COMMENTED** [review]
Do you want to mention the "aha" finding of Compliance Masonry?

**Comment by andrewmaier** [comment]
@afeld @timothybjones Looks good to me!

**Review by andrewmaier — APPROVED** [review]

**Comment by timothybjones** [comment]
Other than my comment above, looks good to me.

**Comment by afeld** [comment]
@timothybjones I think we can wait til we get more anecdotes back from https://github.com/opencontrol/discuss/issues/33, to present all that info together.

Thanks y'all!

**Pull request merged**
